# Generated by Django 3.1.8 on 2021-08-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210810_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogwise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_slug', models.CharField(default='', max_length=300)),
                ('blg_title', models.CharField(max_length=50)),
                ('blg_desc', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
