# Generated by Django 3.1.8 on 2021-08-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogwise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogwise',
            new_name='Blog',
        ),
    ]
